version: '3.8'

services:
  frontend:
    build: ./personalyze-frontend
    ports:
    - 8080:80

  api:
    build: ./personalyze-api
    ports:
    - 5000:5000

  mysqldb:
    image: mysql
    ports:
    - 3000:3306
    environment:
    - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: